apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: debug
      protocol: TCP
      port: 12345
      targetPort: 12345
  type: LoadBalancer